export type BancoBrasileiro = { codigo: string; nome: string }

/**
 * Lista de instituições financeiras participantes do COMPE (Banco Central do Brasil).
 * Fonte: https://www.bcb.gov.br/estabilidadefinanceira/str
 */
export const BANCOS_BRASILEIROS: readonly BancoBrasileiro[] = [
  { codigo: '001', nome: 'BANCO DO BRASIL S.A.' },
  { codigo: '003', nome: 'BANCO DA AMAZONIA S.A.' },
  { codigo: '004', nome: 'BANCO DO NORDESTE DO BRASIL S.A.' },
  { codigo: '007', nome: 'BANCO NACIONAL DE DESENVOLVIMENTO ECONOMICO E SOCIAL' },
  { codigo: '010', nome: 'CREDICOAMO CREDITO RURAL COOPERATIVA' },
  { codigo: '011', nome: 'CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A' },
  { codigo: '012', nome: 'BANCO INBURSA S.A.' },
  { codigo: '014', nome: 'NATIXIS BRASIL S.A. BANCO MULTIPLO' },
  { codigo: '015', nome: 'UBS BRASIL CORRETORA DE CAMBIO, TITULOS E VALORES MOBILIARIOS S.A.' },
  { codigo: '016', nome: 'COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SC E RS' },
  { codigo: '017', nome: 'BNY MELLON BANCO S.A.' },
  { codigo: '018', nome: 'BANCO TRICURY S.A.' },
  { codigo: '021', nome: 'BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO' },
  { codigo: '024', nome: 'BANCO BANDEPE S.A.' },
  { codigo: '025', nome: 'BANCO ALFA S.A.' },
  { codigo: '029', nome: 'BANCO ITAÚ CONSIGNADO S.A.' },
  { codigo: '033', nome: 'BANCO SANTANDER (BRASIL) S.A.' },
  { codigo: '036', nome: 'BANCO BRADESCO BBI S.A.' },
  { codigo: '037', nome: 'BANCO DO ESTADO DO PARÁ S.A.' },
  { codigo: '040', nome: 'BANCO CARGILL S.A.' },
  { codigo: '041', nome: 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.' },
  { codigo: '047', nome: 'BANCO DO ESTADO DE SERGIPE S.A.' },
  { codigo: '060', nome: 'CONFIDENCE CORRETORA DE CÂMBIO S.A.' },
  { codigo: '062', nome: 'HIPERCARD BANCO MULTIPLO S.A.' },
  { codigo: '063', nome: 'BANCO BRADESCARD S.A.' },
  { codigo: '064', nome: 'GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A.' },
  { codigo: '065', nome: 'BANCO ANDBANK (BRASIL) S.A.' },
  { codigo: '066', nome: 'BANCO MORGAN STANLEY S.A.' },
  { codigo: '069', nome: 'BANCO CREFISA S.A.' },
  { codigo: '070', nome: 'BRB - BANCO DE BRASILIA S.A.' },
  { codigo: '074', nome: 'BCO. J.SAFRA S.A.' },
  { codigo: '075', nome: 'BANCO ABN AMRO S.A.' },
  { codigo: '076', nome: 'BANCO KDB DO BRASIL S.A.' },
  { codigo: '077', nome: 'BANCO INTER S.A.' },
  { codigo: '078', nome: 'HAITONG BANCO DE INVESTIMENTO DO BRASIL S.A.' },
  { codigo: '079', nome: 'PICPAY BANK - BANCO MULTIPLE S.A' },
  { codigo: '080', nome: 'B&T CORRETORA DE CAMBIO LTDA.' },
  { codigo: '081', nome: 'BANCOSEGURO S.A.' },
  { codigo: '082', nome: 'BANCO TOPÁZIO S.A.' },
  { codigo: '083', nome: 'BANCO DA CHINA BRASIL S.A.' },
  { codigo: '084', nome: 'UNIPRIME NORTE DO PARANÁ - COOPERATIVA DE CRÉDITO' },
  { codigo: '085', nome: 'COOPERATIVA CENTRAL DE CRÉDITO - AILOS' },
  { codigo: '088', nome: 'BANCO RANDON S.A.' },
  { codigo: '089', nome: 'COOPERATIVA DE CRÉDITO RURAL DA REGIÃO DA MOGIANA' },
  { codigo: '091', nome: 'CENTRAL DE COOPERATIVAS DE ECONOMIA E CRÉDITO MÚTUO DO EST RS' },
  { codigo: '092', nome: 'BRK S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '093', nome: 'PÓLOCRED SCMEPP LTDA.' },
  { codigo: '094', nome: 'BANCO FINAXIS S.A.' },
  { codigo: '095', nome: 'TRAVELEX BANCO DE CÂMBIO S.A.' },
  { codigo: '096', nome: 'BANCO B3 S.A.' },
  { codigo: '097', nome: 'CREDISIS - CENTRAL DE COOPERATIVAS DE CRÉDITO DO NORTE DO BRASIL' },
  { codigo: '098', nome: 'CREDIALIANÇA COOPERATIVA DE CRÉDITO RURAL' },
  { codigo: '099', nome: 'UNIPRIME CENTRAL - CENTRAL INTERESTADUAL DE COOPERATIVAS DE CRÉDITO' },
  { codigo: '100', nome: 'PLANNER CORRETORA DE VALORES S.A.' },
  { codigo: '101', nome: 'RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' },
  { codigo: '102', nome: 'XP INVESTIMENTOS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '104', nome: 'CAIXA ECONOMICA FEDERAL' },
  { codigo: '105', nome: 'LECCA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A' },
  { codigo: '107', nome: 'BANCO BOCOM BBM S.A.' },
  { codigo: '108', nome: 'PORTOCRED S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '111', nome: 'OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.' },
  { codigo: '113', nome: 'MAGLIANO S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS' },
  { codigo: '114', nome: 'CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ES - CECOOP' },
  { codigo: '117', nome: 'ADVANCED CORRETORA DE CÂMBIO LTDA' },
  { codigo: '119', nome: 'BANCO WESTERN UNION DO BRASIL S.A.' },
  { codigo: '120', nome: 'BANCO RODOBENS S.A.' },
  { codigo: '121', nome: 'BANCO AGIBANK S.A.' },
  { codigo: '122', nome: 'BANCO BRADESCO BERJ S.A.' },
  { codigo: '124', nome: 'BANCO WOORI BANK DO BRASIL S.A.' },
  { codigo: '125', nome: 'BANCO GENIAL S.A.' },
  { codigo: '126', nome: 'BR PARTNERS BANCO DE INVESTIMENTO S.A.' },
  { codigo: '127', nome: 'CODEPE CORRETORA DE VALORES E CÂMBIO S.A.' },
  { codigo: '128', nome: 'BRAZA BANK S.A. BANCO DE CÂMBIO' },
  { codigo: '129', nome: 'UBS BB BANCO DE INVESTIMENTO S.A.' },
  { codigo: '130', nome: 'CARUANA S.A. SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '131', nome: 'TULLETT PREBON BRASIL COR. DE VALORES E CÂMBIO LTDA' },
  { codigo: '132', nome: 'ICBC DO BRASIL BANCO MULTIPLO S.A.' },
  { codigo: '133', nome: 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA' },
  { codigo: '134', nome: 'BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' },
  { codigo: '135', nome: 'GRADUAL CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '136', nome: 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA' },
  { codigo: '137', nome: 'MULTIMONEY CORRETORA DE CÂMBIO LTDA' },
  { codigo: '138', nome: 'GET MONEY CORRETORA DE CÂMBIO S.A.' },
  { codigo: '139', nome: 'INTESA SANPAOLO BRASIL S.A. BANCO MULTIPLO' },
  { codigo: '140', nome: 'EASYNVEST - TÍTULO CORRETORA DE VALORES SA' },
  { codigo: '142', nome: 'BROKER BRASIL CORRETORA DE CÂMBIO LTDA.' },
  { codigo: '143', nome: 'TREVISO CORRETORA DE CÂMBIO S.A.' },
  { codigo: '144', nome: 'BEXS BANCO DE CÂMBIO S.A.' },
  { codigo: '145', nome: 'LEVYCAM - CORRETORA DE CAMBIO E VALORES LTDA.' },
  { codigo: '146', nome: 'GUITTA CORRETORA DE CAMBIO LTDA' },
  { codigo: '149', nome: 'FACTA FINANCEIRA S.A. - CRÉDITO FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '157', nome: 'ICAP DO BRASIL CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '159', nome: 'CASA DO CRÉDITO S.A. SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR' },
  { codigo: '163', nome: 'COMMERZBANK BRASIL S.A. BANCO MÚLTIPLO' },
  { codigo: '169', nome: 'BANCO OLÉ CONSIGNADO S.A.' },
  { codigo: '172', nome: 'ALBATROSS CORRETORA DE CAMBIO E VALORES S.A' },
  { codigo: '173', nome: 'BRL TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '174', nome: 'PERNAMBUCANAS FINANCIADORA S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '177', nome: 'GUIDE INVESTIMENTOS S.A. CORRETORA DE VALORES' },
  { codigo: '180', nome: 'CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS LTDA' },
  { codigo: '182', nome: 'DACASA FINANCEIRA S/A - SCFI' },
  { codigo: '183', nome: 'SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE' },
  { codigo: '184', nome: 'BANCO ITAÚ BBA S.A.' },
  { codigo: '188', nome: 'ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES' },
  { codigo: '189', nome: 'HS FINANCEIRA S/A CRÉDITO, FINANCIAMENTO E INVESTIMENTOS' },
  { codigo: '190', nome: 'SERVICOOP - COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RS' },
  { codigo: '191', nome: 'NOVA FUTURA CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '194', nome: 'PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' },
  { codigo: '196', nome: 'FAIR CORRETORA DE CÂMBIO S.A.' },
  { codigo: '197', nome: 'STONE PAGAMENTOS S.A.' },
  { codigo: '208', nome: 'BANCO BTG PACTUAL S.A.' },
  { codigo: '212', nome: 'BANCO ORIGINAL S.A.' },
  { codigo: '213', nome: 'BANCO ARBI S.A.' },
  { codigo: '217', nome: 'BANCO JOHN DEERE S.A.' },
  { codigo: '218', nome: 'BANCO BS2 S.A.' },
  { codigo: '222', nome: 'BANCO CRÉDIT AGRICOLE BRASIL S.A.' },
  { codigo: '224', nome: 'BANCO FIBRA S.A.' },
  { codigo: '233', nome: 'BANCO CIFRA S.A.' },
  { codigo: '237', nome: 'BANCO BRADESCO S.A.' },
  { codigo: '241', nome: 'BANCO CLASSICO S.A.' },
  { codigo: '243', nome: 'BANCO MASTER S/A' },
  { codigo: '246', nome: 'BANCO ABC BRASIL S.A.' },
  { codigo: '249', nome: 'BANCO INVESTCRED UNIBANCO S.A.' },
  { codigo: '250', nome: 'BCV - BANCO DE CRÉDITO E VAREJO S/A' },
  { codigo: '253', nome: 'BEXS CORRETORA DE CÂMBIO S/A' },
  { codigo: '254', nome: 'PARANÁ BANCO S.A.' },
  { codigo: '259', nome: 'MONEYCORP BANCO DE CÂMBIO S.A.' },
  { codigo: '260', nome: 'NU PAGAMENTOS S.A. (NUBANK)' },
  { codigo: '265', nome: 'BANCO FATOR S.A.' },
  { codigo: '266', nome: 'BANCO CEDULA S.A.' },
  { codigo: '268', nome: 'BARIGUI COMPANHIA HIPOTECÁRIA' },
  { codigo: '269', nome: 'HSBC BRASIL S.A. BANCO DE INVESTIMENTO' },
  { codigo: '270', nome: 'SAGITUR CORRETORA DE CÂMBIO LTDA.' },
  { codigo: '271', nome: 'IB CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '272', nome: 'AGK CORRETORA DE CAMBIO S.A.' },
  { codigo: '273', nome: 'COOPERATIVA DE CRÉDITO RURAL DE SÃO MIGUEL DO OESTE' },
  { codigo: '274', nome: 'MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO POR' },
  { codigo: '276', nome: 'SENFF S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '278', nome: 'GENIAL INVESTIMENTOS CORRETORA DE VALORES MOBILIÁRIOS S.A.' },
  { codigo: '279', nome: 'COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE' },
  { codigo: '280', nome: 'AVISTA S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '281', nome: 'COOPERATIVA DE CRÉDITO RURAL COOPAVEL' },
  { codigo: '283', nome: 'RB INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '285', nome: 'FRENTE CORRETORA DE CÂMBIO LTDA.' },
  { codigo: '286', nome: 'COOPERATIVA DE CRÉDITO RURAL DE OURO' },
  { codigo: '288', nome: 'CAROL DISTRIBUIDORA DE TÍTULOS E VALOR MOBILIÁRIOS LTDA.' },
  { codigo: '289', nome: 'DECYSEO CORRETORA DE CAMBIO LTDA.' },
  { codigo: '290', nome: 'PAGSEGURO INTERNET S.A.' },
  { codigo: '292', nome: 'BS2 DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '293', nome: 'LASTRO RDV DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '296', nome: 'VISION S.A. CORRETORA DE CÂMBIO' },
  { codigo: '298', nome: 'VIPS CC LTDA.' },
  { codigo: '299', nome: 'BANCO SOROCRED S.A. - BANCO MÚLTIPLO' },
  { codigo: '300', nome: 'BANCO DE LA NACION ARGENTINA' },
  { codigo: '301', nome: 'BPP INSTITUIÇÃO DE PAGAMENTO S.A.' },
  { codigo: '306', nome: 'PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.' },
  { codigo: '307', nome: 'TERRA INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '309', nome: 'CAMBIONET CORRETORA DE CÂMBIO LTDA.' },
  { codigo: '310', nome: 'VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.' },
  { codigo: '311', nome: 'DOURADA CORRETORA DE CÂMBIO LTDA.' },
  { codigo: '312', nome: 'HSCM - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE' },
  { codigo: '313', nome: 'AMAZÔNIA CORRETORA DE CÂMBIO LTDA.' },
  { codigo: '315', nome: 'PI DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '318', nome: 'BANCO BMG S.A.' },
  { codigo: '319', nome: 'OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' },
  { codigo: '320', nome: 'BANCO CCB BRASIL S.A.' },
  { codigo: '321', nome: 'CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE' },
  { codigo: '322', nome: 'COOPERATIVA DE CRÉDITO RURAL DE ABELARDO LUZ' },
  { codigo: '323', nome: 'MERCADO PAGO - BANCO' },
  { codigo: '324', nome: 'CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '325', nome: 'ÓRAMA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '326', nome: 'PARATI - CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.' },
  { codigo: '328', nome: 'CECM DOS FUNCIONÁRIOS DO BANCO CENTRAL DO BRASIL' },
  { codigo: '329', nome: 'QI SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '330', nome: 'BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S/A' },
  { codigo: '331', nome: 'FRAM CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '332', nome: 'ACESSO SOLUÇÕES DE PAGAMENTO S.A.' },
  { codigo: '335', nome: 'BANCO DIGIO S.A.' },
  { codigo: '336', nome: 'BANCO C6 S.A.' },
  { codigo: '340', nome: 'SUPER PAGAMENTOS E ADMINISTRACAO DE MEIOS ELETRONICOS S.A.' },
  { codigo: '341', nome: 'ITAÚ UNIBANCO S.A.' },
  { codigo: '342', nome: 'CREDITAS SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '343', nome: 'FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE' },
  { codigo: '348', nome: 'BANCO XP S.A.' },
  { codigo: '349', nome: 'AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '350', nome: 'COOPERATIVA DE CRÉDITO RURAL DE PEQUENOS AGRICULTORES E DA REFORMA AGRÁRIA' },
  { codigo: '352', nome: 'TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' },
  { codigo: '354', nome: 'NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES' },
  { codigo: '355', nome: 'ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '356', nome: 'ACCOUNT PAGAMENTOS S.A.' },
  { codigo: '358', nome: 'MIDWAY S.A. - SCFI' },
  { codigo: '359', nome: 'ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A' },
  { codigo: '360', nome: 'TRINUS CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '362', nome: 'CIELO S.A.' },
  { codigo: '363', nome: 'SINGULARE CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '364', nome: 'GERENCIANET PAGAMENTOS DO BRASIL LTDA' },
  { codigo: '365', nome: 'SIMPAUL CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A.' },
  { codigo: '366', nome: 'BANCO SOCIETE GENERALE BRASIL S.A.' },
  { codigo: '367', nome: 'VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '368', nome: 'BANCO CSF S.A.' },
  { codigo: '370', nome: 'BANCO MIZUHO DO BRASIL S.A.' },
  { codigo: '371', nome: 'WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMBIO LTDA.' },
  { codigo: '372', nome: 'JUMP SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '373', nome: 'UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.' },
  { codigo: '374', nome: 'REALIZE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.' },
  { codigo: '376', nome: 'BANCO J.P. MORGAN S.A.' },
  { codigo: '377', nome: 'BMS SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '378', nome: 'BBC LEASING S.A. - ARRENDAMENTO MERCANTIL' },
  { codigo: '379', nome: 'COOPERFORTE - COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DE FUNCIONÁRIOS' },
  { codigo: '380', nome: 'PICPAY SERVIÇOS S.A.' },
  { codigo: '381', nome: 'BANCO MERCEDES-BENZ DO BRASIL S.A.' },
  { codigo: '382', nome: 'FIDUCIA SCMEPP LTDA' },
  { codigo: '383', nome: 'EBANX IP LTDA.' },
  { codigo: '384', nome: 'GLOBAL FINANÇAS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO' },
  { codigo: '385', nome: 'COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS TRABALHADORES PORTUÁRIOS' },
  { codigo: '386', nome: 'NU FINANCEIRA S.A. - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '387', nome: 'BANCO TOYOTA DO BRASIL S.A.' },
  { codigo: '388', nome: 'COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS ELETRICITÁRIOS E TRABALHADORES' },
  { codigo: '389', nome: 'BANCO MERCANTIL DO BRASIL S.A.' },
  { codigo: '390', nome: 'BANCO GM S.A.' },
  { codigo: '391', nome: 'COOPERATIVA DE CRÉDITO RURAL SULCREDI/COBEL' },
  { codigo: '393', nome: 'BANCO VOLKSWAGEN S.A.' },
  { codigo: '394', nome: 'BANCO BRADESCO FINANCIAMENTOS S.A.' },
  { codigo: '395', nome: 'F.D\'GOLD - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '396', nome: 'HUB PAGAMENTOS S.A.' },
  { codigo: '397', nome: 'LETSBANK S.A. - BANCO MÚLTIPLO' },
  { codigo: '398', nome: 'IDEAL CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '399', nome: 'KIRTON BANK S.A. - BANCO MÚLTIPLO' },
  { codigo: '400', nome: 'COOPERATIVA DE CRÉDITO, POUPANÇA E SERVIÇOS FINANCEIROS DO CENTRO OESTE' },
  { codigo: '401', nome: 'IUGU INSTITUIÇÃO DE PAGAMENTO S.A.' },
  { codigo: '402', nome: 'COBUCCIO SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '403', nome: 'CORA SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '404', nome: 'SUMUP SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '406', nome: 'ACCREDITO - SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '407', nome: 'ÍNDIGO INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '408', nome: 'BONUSPAGO SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '410', nome: 'PLANNER SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '411', nome: 'VIA CERTA FINANCIADORA S.A.' },
  { codigo: '412', nome: 'BANCO CAPITAL S.A.' },
  { codigo: '413', nome: 'BANCO BV S.A.' },
  { codigo: '414', nome: 'WORK SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '415', nome: 'LAMARA SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '416', nome: 'LEROYMERLIN COMPANHIA HIPOTECÁRIA' },
  { codigo: '418', nome: 'ZIPDIN SOLUÇÕES DIGITAIS SOCIEDADE DE CRÉDITO DIRETO S/A' },
  { codigo: '419', nome: 'NUMBRS SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '421', nome: 'LAR COOPERATIVA DE CRÉDITO - LAR CREDI' },
  { codigo: '422', nome: 'BANCO SAFRA S.A.' },
  { codigo: '423', nome: 'COLUNA S/A DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS' },
  { codigo: '425', nome: 'SOCINAL S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '426', nome: 'BIORC FINANCEIRA - CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.' },
  { codigo: '427', nome: 'COOPERATIVA DE CRÉDITO DOS SERVIDORES DA UNIVERSIDADE FEDERAL DO ESPÍRITO SANTO' },
  { codigo: '428', nome: 'CRED-SYSTEM SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO' },
  { codigo: '429', nome: 'CREDISMITH SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '430', nome: 'COOPERATIVA DE CREDITO RURAL SEARA - CREDISEARA' },
  { codigo: '431', nome: 'INSTITUTO DE PAGAMENTOS ESPECIALIZADOS (IPE)' },
  { codigo: '433', nome: 'BR-CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '435', nome: 'DELCRED SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '438', nome: 'PLANNER TRUSTEE DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '439', nome: 'ID CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '440', nome: 'CREDIBELO S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQ' },
  { codigo: '441', nome: 'MAGNETIS - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' },
  { codigo: '442', nome: 'MAGNETIS SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '443', nome: 'CREDIHOME SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '444', nome: 'TRINUS SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '445', nome: 'PLANTAE S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '447', nome: 'MIRAE ASSET CORRETORA DE CAMBIO E VALORES MOBILIARIOS LTDA' },
  { codigo: '448', nome: 'HEMERA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '449', nome: 'DMCARD SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '450', nome: 'FITBANK PAGAMENTOS ELETRONICOS S.A.' },
  { codigo: '451', nome: 'J17 - SOCIEDADE DE CRÉDITO DIRETO S/A' },
  { codigo: '452', nome: 'CREDIFIT SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '453', nome: 'MÉRITO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '454', nome: 'MÉRITO FINANCEIRA S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '455', nome: 'FÊNIX DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '456', nome: 'BANCO MUFG BRASIL S.A.' },
  { codigo: '457', nome: 'UY3 SOCIEDADE DE CRÉDITO DIRETO S/A' },
  { codigo: '458', nome: 'HEDGE INVESTMENTS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '459', nome: 'COOPERATIVA DE CRÉDITO DOS MÉDICOS E DEMAIS PROFISSIONAIS DA SAÚDE' },
  { codigo: '460', nome: 'UNAVANTI SOCIEDADE DE CRÉDITO DIRETO S/A' },
  { codigo: '461', nome: 'ASAAS GESTÃO FINANCEIRA INSTITUIÇÃO DE PAGAMENTO S.A.' },
  { codigo: '462', nome: 'STARK SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '463', nome: 'AZUMI DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '464', nome: 'BANCO SUMITOMO MITSUI BRASILEIRO S.A.' },
  { codigo: '465', nome: 'CAPITAL CONSIG SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '467', nome: 'MASTER S/A CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS' },
  { codigo: '468', nome: 'PORTOSEG S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '469', nome: 'LIGA INVEST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '470', nome: 'CDC SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE' },
  { codigo: '471', nome: 'COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS SERVIDORES DO MUNICÍPIO DE NITERÓI' },
  { codigo: '473', nome: 'BANCO CAIXA GERAL - BRASIL S.A.' },
  { codigo: '477', nome: 'CITIBANK N.A.' },
  { codigo: '478', nome: 'GAZINCRED S.A. SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '479', nome: 'BANCO ITAUBANK S.A.' },
  { codigo: '484', nome: 'MAF DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '487', nome: 'DEUTSCHE BANK S.A. BANCO ALEMAO' },
  { codigo: '488', nome: 'JPMORGAN CHASE BANK, NATIONAL ASSOCIATION' },
  { codigo: '492', nome: 'ING BANK N.V.' },
  { codigo: '495', nome: 'BANCO DE LA PROVINCIA DE BUENOS AIRES' },
  { codigo: '505', nome: 'BANCO CREDIT SUISSE (BRASIL) S.A.' },
  { codigo: '506', nome: 'RJI CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' },
  { codigo: '507', nome: 'SCFI PORTOSEG S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '508', nome: 'AVENUE SECURITIES DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '510', nome: 'FITBANK HOLDINGS ADMINISTRADORA DE SERVIÇOS E PAGAMENTOS LTDA.' },
  { codigo: '511', nome: 'MAGNUM SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '512', nome: 'CAPITUAL INSTITUIÇÃO DE PAGAMENTO S.A.' },
  { codigo: '513', nome: 'BANCOSEGURO S.A.' },
  { codigo: '516', nome: 'QISTA S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '518', nome: 'MERCADO CRÉDITO SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.' },
  { codigo: '519', nome: 'LIONS TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '520', nome: 'SOMAPAY SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '521', nome: 'PEAK SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.' },
  { codigo: '523', nome: 'HR DIGITAL SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '524', nome: 'WNT CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '525', nome: 'INTERCAM CORRETORA DE CÂMBIO LTDA.' },
  { codigo: '527', nome: 'ATICCA - SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '528', nome: 'REAG TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '529', nome: 'PINBANK BRASIL INSTITUIÇÃO DE PAGAMENTO S.A.' },
  { codigo: '530', nome: 'SER FINANCE SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '531', nome: 'BMP SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA' },
  { codigo: '532', nome: 'EAGLE SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '533', nome: 'SRM BANK - BANCO MÚLTIPLO S.A.' },
  { codigo: '534', nome: 'EWALLY TECNOLOGIA E SERVIÇO S.A.' },
  { codigo: '535', nome: 'OPEA SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '536', nome: 'NEON PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO' },
  { codigo: '537', nome: 'MICROCASH SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE' },
  { codigo: '538', nome: 'SUDACRED S.A. SOCIEDADE DE CRÉDITO DIRETO' },
  { codigo: '539', nome: 'SANTINVEST S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTOS' },
  { codigo: '540', nome: 'HB SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE S.A.' },
  { codigo: '541', nome: 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (FGTS)' },
  { codigo: '543', nome: 'COOPERATIVA DE CRÉDITO DOS SERVIDORES MUNICIPAIS DE PIRACICABA' },
  { codigo: '545', nome: 'SENSO CORRETORA DE CÂMBIO E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '546', nome: 'U4C INSTITUIÇÃO DE PAGAMENTO S.A.' },
  { codigo: '548', nome: 'RPW S.A. SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { codigo: '549', nome: 'INTRA INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.' },
  { codigo: '550', nome: 'BEETELLER INSTITUIÇÃO DE PAGAMENTO LTDA.' },
  { codigo: '552', nome: 'VERT CAPITAL SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '553', nome: 'PERCAPITA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE' },
  { codigo: '556', nome: 'ATIVOS S.A. SECURITIZADORA DE CRÉDITOS FINANCEIROS' },
  { codigo: '558', nome: 'ZIPCODE PAGAMENTOS S.A.' },
  { codigo: '559', nome: 'KANASTRA SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '560', nome: 'MAI SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { codigo: '562', nome: 'AZIMUT BRASIL RIQUEZA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { codigo: '563', nome: 'OMNI BANCO S.A.' },
  { codigo: '565', nome: 'ACESSO BANK BANK BRASIL INSTITUIÇÃO DE PAGAMENTO S.A.' },
  { codigo: '566', nome: 'NUMBRS CORRETORA DE CÂMBIO LTDA.' },
  { codigo: '568', nome: 'TPAG INSTITUIÇÃO DE PAGAMENTO LTDA' },
  { codigo: '600', nome: 'BANCO LUSO BRASILEIRO S.A.' },
  { codigo: '604', nome: 'BANCO INDUSTRIAL DO BRASIL S.A.' },
  { codigo: '610', nome: 'BANCO VR S.A.' },
  { codigo: '611', nome: 'BANCO PAULISTA S.A.' },
  { codigo: '612', nome: 'BANCO GUANABARA S.A.' },
  { codigo: '613', nome: 'OMNI BANCO S.A.' },
  { codigo: '623', nome: 'BANCO PAN S.A.' },
  { codigo: '626', nome: 'BANCO C6 CONSIGNADO S.A.' },
  { codigo: '630', nome: 'BANCO SMARTBANK S.A.' },
  { codigo: '633', nome: 'BANCO RENDIMENTO S.A.' },
  { codigo: '634', nome: 'BANCO TRIANGULO S.A.' },
  { codigo: '637', nome: 'BANCO SOFISA S.A.' },
  { codigo: '643', nome: 'BANCO PINE S.A.' },
  { codigo: '652', nome: 'ITAÚ UNIBANCO HOLDING S.A.' },
  { codigo: '653', nome: 'BANCO INDUSVAL S.A.' },
  { codigo: '654', nome: 'BANCO A.J. RENNER S.A.' },
  { codigo: '655', nome: 'BANCO VOTORANTIM S.A.' },
  { codigo: '707', nome: 'BANCO DAYCOVAL S.A.' },
  { codigo: '712', nome: 'BANCO OURINVEST S.A.' },
  { codigo: '739', nome: 'BANCO CETELEM S.A.' },
  { codigo: '741', nome: 'BANCO RIBEIRAO PRETO S.A.' },
  { codigo: '743', nome: 'BANCO SEMEAR S.A.' },
  { codigo: '745', nome: 'BANCO CITIBANK S.A.' },
  { codigo: '746', nome: 'BANCO MODAL S.A.' },
  { codigo: '747', nome: 'BANCO RABOBANK INTERNATIONAL BRASIL S.A.' },
  { codigo: '748', nome: 'BANCO COOPERATIVO SICREDI S.A.' },
  { codigo: '751', nome: 'SCOTIABANK BRASIL S.A. BANCO MÚLTIPLO' },
  { codigo: '752', nome: 'BANCO BNP PARIBAS BRASIL S.A.' },
  { codigo: '753', nome: 'NOVO BANCO CONTINENTAL S.A. BANCO MULTIPLO' },
  { codigo: '754', nome: 'BANCO SISTEMA S.A.' },
  { codigo: '755', nome: 'BANK OF AMERICA MERRILL LYNCH BANCO MULTIPLO S.A.' },
  { codigo: '756', nome: 'BANCO SICOOB DO BRASIL S.A.' },
  { codigo: '757', nome: 'BANCO KEB HANA DO BRASIL S.A.' },
]
